INSERT INTO series (title, author_id, subgenre_id) VALUES ("jesus lives", 2, 2);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("jesus lives", 2, 2);
INSERT INTO books (title, year, series_id) VALUES ("poopies", 2001, 2);
INSERT INTO books (title, year, series_id) VALUES ("poopies", 2001, 2);
INSERT INTO books (title, year, series_id) VALUES ("poopies", 2001, 2);
INSERT INTO books (title, year, series_id) VALUES ("poopies", 2001, 2);
INSERT INTO books (title, year, series_id) VALUES ("poopies", 2001, 2);
INSERT INTO books (title, year, series_id) VALUES ("poopies", 2001, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("foooord", "i am kings", "mutant", 2, 1);
INSERT INTO subgenres (name) VALUES ("hope");
INSERT INTO subgenres (name) VALUES ("love");
INSERT INTO authors (name) VALUES ("Moothe");
INSERT INTO authors (name) VALUES ("Soooom");
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
